# -*- coding: utf-8 -*-
"""Vajra_15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-bp02yNhCj8axD-8wsf8kwMNRLoyaYDA

#pure to generative nn
"""

import numpy as np

class VajraBridgeEngine:
    def __init__(self, input_dim=384, topology_config=[256, 128, 64], num_classes=4, vocab_size=15000, gold_mask=None):
        self.dim = input_dim
        self.config = topology_config
        self.vocab_size = vocab_size
        self.num_classes = num_classes
        self.layers = []

        # --- DYNAMIC DIMENSION MAPPING ---
        self.dims = [input_dim]
        decay = (input_dim - 64) // len(topology_config)
        for i in range(len(topology_config)):
            if i == len(topology_config) - 1:
                self.dims.append(64)
            else:
                self.dims.append(self.dims[-1] - decay)

        # 🛰️ DYNAMIC GOLD MASK
        self.gold_mask = gold_mask if gold_mask is not None else np.full(vocab_size, 0.1, dtype=np.float32)

        # Frequency and Sequence Tracking
        self.freq_map = np.zeros(vocab_size, dtype=np.float32)
        self.pos_map = np.zeros(vocab_size, dtype=np.float32)

        # Initialize MoE Graph Layers
        for i in range(len(topology_config)):
            d_in = self.dims[i]
            d_out = self.dims[i+1]
            n_experts = topology_config[i]
            self.layers.append(VajraGraphLayer(n_in_experts=n_experts, dim_in=d_in, dim_out=d_out))

        final_dim = self.dims[-1]

        # --- ADAM OPTIMIZED HEADS ---
        self.head = (np.random.randn(final_dim, num_classes) * np.sqrt(2/final_dim)).astype(np.float32)
        self.m_head, self.v_head = np.zeros_like(self.head), np.zeros_like(self.head)

        self.speech_head = (np.random.randn(final_dim, vocab_size) * np.sqrt(1/final_dim)).astype(np.float32)

        self.m_speech, self.v_speech = np.zeros_like(self.speech_head), np.zeros_like(self.speech_head)

        self.history_vault = None
        self.ltm_buffer = None

    def snapshot_history(self):
        """🔱 SECTION V-C: THE REGULARIZATION ANCHOR"""
        self.history_vault = {
            "layers": [np.copy(l.W_experts) for l in self.layers],
            "head": np.copy(self.head),
            "speech_head": np.copy(self.speech_head)
        }
        self.ltm_buffer = np.zeros((1, self.dims[-1]), dtype=np.float32)

    def update_ltm(self, current_signal):
        if self.ltm_buffer is None:
            self.ltm_buffer = np.copy(current_signal)
        else:
            self.ltm_buffer = (0.85 * self.ltm_buffer) + (0.15 * current_signal)

    def calculate_hash_influence(self, token_id, pos):
        last_was_gold = self.gold_mask[token_id] >= 0.8
        if pos < 2: return 1.4
        if last_was_gold:
            influence = 0.65
        else:
            influence = 1.0 + (1.0 / (1.0 + np.exp(-(pos - 5)))) * 0.4

        freq = self.freq_map[token_id]
        if freq > 0:
            influence *= (1.0 / (1.0 + np.log1p(freq * 0.5)))
        return np.clip(influence, 0.1, 1.8)

    def forward(self, x, query_anchor=None, current_pos=0, last_token_id=None, is_training=True, target_expert=None):
        if x.ndim == 1: x = x.reshape(1, -1)
        current_signal = x

        # 1. Query Injection
        if query_anchor is not None:
            if query_anchor.ndim == 1: query_anchor = query_anchor.reshape(1, -1)
            anchor_weight = 0.3 if current_pos < 5 else 0.15
            current_signal = ((1 - anchor_weight) * current_signal) + (anchor_weight * query_anchor)

        all_caches = []
        # 2. Sequential MoE Processing
        for i, layer in enumerate(self.layers):
            current_signal, cache = layer.forward(current_signal, is_training=is_training)
            all_caches.append(cache)

            if i == len(self.layers) - 1 and self.ltm_buffer is not None:
                current_signal = (0.92 * current_signal) + (0.08 * self.ltm_buffer)

        # 3. GDI Attention
        current_signal = self.apply_gdi_attention(current_signal, is_training=is_training)

        # 4. Temporal Influence
        if last_token_id is not None:
            influence = self.calculate_hash_influence(last_token_id, current_pos)
            current_signal *= influence

        if not is_training:
            self.update_ltm(current_signal)

        # 5. Projections
        expert_logits = np.dot(current_signal, self.head)
        if target_expert is not None:
            expert_logits.fill(-1e4)
            expert_logits[0, target_expert] = 1e4

        word_logits = np.dot(current_signal, self.speech_head)
        word_logits = (word_logits - np.mean(word_logits)) / (np.std(word_logits) + 1e-8)

        # 6. Inference Warping
        if not is_training and self.gold_mask is not None:
            if current_pos % 2 == 0:
                word_logits += (self.gold_mask * 2.5)
            else:
                word_logits += ((1.0 - self.gold_mask) * 3.5)
                word_logits -= (self.gold_mask * 2.0)

        return expert_logits, word_logits, (all_caches, current_signal)

    def apply_gdi_attention(self, x, is_training=True):
         final_dim = self.dims[-1]
         gdi_scale = np.sqrt(final_dim)
         global_avg = np.mean(np.abs(x), axis=1, keepdims=True)
         importance_scores = global_avg * gdi_scale
         mask = np.where(importance_scores >= 0.5, 1.05, 0.95) if is_training else 1.0
         return x * mask

    def train_step_raw(self, x_word, q_anchor, target_expert_oh, target_word_indices, epoch=0, lambda_val=0.7, smoothing=0.1, pos=0):
        """🔱 VAJRA 11.2 UPGRADED TRAINING STEP"""
        batch_size = x_word.shape[0]

        for idx in target_word_indices:
            self.freq_map[idx] += 1
            self.pos_map[idx] = pos

        last_tok = target_word_indices[0] if pos > 0 else 1

        exp_logits, word_logits, (caches, final_out) = self.forward(
            x_word, query_anchor=q_anchor, current_pos=pos, last_token_id=last_tok, is_training=True
        )

        word_logits[:, [0, 1, 3]] = -1e9
        word_pred = self.softmax(word_logits)
        exp_pred = self.softmax(exp_logits)

        # --- LOSS A: ROUTING DOMAINS (Primary Priority) ---
        exp_loss = -np.mean(np.sum(target_expert_oh * np.log(exp_pred + 1e-10), axis=-1))

        # --- LOSS B: LINGUISTIC WORD PREDICTION ---
        mask_vals = self.gold_mask[target_word_indices]
        dynamic_smoothing = np.where(mask_vals >= 0.8, smoothing * 0.5, smoothing)
        smoothed_target = np.full_like(word_pred, (dynamic_smoothing / (self.vocab_size - 3))[:, np.newaxis])
        for b in range(batch_size):
            smoothed_target[b, target_word_indices[b]] = 1.0 - dynamic_smoothing[b]

        #loss_weights = np.where(mask_vals >= 0.8, 2.0, 4.0)
        loss_weights = mask_vals
        word_loss = np.mean(-np.sum(smoothed_target * np.log(word_pred + 1e-10), axis=-1) * loss_weights)

        # --- LOSS C: DIVERSITY PENALTY (Prevents Expert Collapse) ---
        router_probs = np.mean(exp_pred, axis=0)
        cv_squared = np.var(router_probs) / (np.mean(router_probs)**2 + 1e-10)
        load_balance_loss = 0.2 * cv_squared

        # --- LOSS D: CHECKPOINT REGULARIZATION (Historical Tethering) ---
        reg_loss = 0
        if self.history_vault is not None:
            for i, layer in enumerate(self.layers):
                # Penalize drift from the 'Solid' configuration
                reg_loss += 0.002 * np.mean((layer.W_experts - self.history_vault['layers'][i])**2)

        # TOTAL CONVERGENCE LOSS
        total_loss = (lambda_val * exp_loss) + ((1 - lambda_val) * word_loss) + load_balance_loss + reg_loss

        # Backward Flow
        d_exp_logits = (lambda_val * (exp_pred - target_expert_oh)) / batch_size
        d_word_logits = ((1 - lambda_val) * (word_pred - smoothed_target) * loss_weights[:, np.newaxis]) / batch_size
        d_word_logits = np.clip(d_word_logits, -0.1, 0.1)

        d_head = np.dot(final_out.T, d_exp_logits)
        d_speech_head = np.dot(final_out.T, d_word_logits)
        d_current_signal = np.dot(d_exp_logits, self.head.T) + np.dot(d_word_logits, self.speech_head.T)

        layer_grads = []
        for i in reversed(range(len(self.layers))):
            d_current_signal, grads = self.layers[i].backward(d_current_signal, caches[i])
            layer_grads.append(grads)

        return total_loss, d_head, d_speech_head, layer_grads[::-1], exp_pred, word_pred

    def apply_batch_update(self, d_head, d_speech_head, layer_grads, lr):
        self.apply_adam(self.head, d_head, self.m_head, self.v_head, lr, weight_decay=1e-4)
        self.apply_adam(self.speech_head, d_speech_head, self.m_speech, self.v_speech, lr, weight_decay=1e-5)
        for i, layer in enumerate(self.layers):
            dW, dR, dB, dAlpha = layer_grads[i]
            self.apply_adam(layer.W_experts, dW, layer.m_W, layer.v_W, lr)
            self.apply_adam(layer.W_router, dR, layer.m_R, layer.v_R, lr)
            self.apply_adam(layer.W_bridge, dB, layer.m_B, layer.v_B, lr)
            self.apply_adam(layer.bridge_alpha, dAlpha, layer.m_alpha, layer.v_alpha, lr,weight_decay=1e-2)

    def apply_adam(self, W, grad, m, v, lr, b1=0.9, b2=0.999, eps=1e-8, weight_decay=0.0):
        grad = np.clip(grad, -1.0, 1.0)
        if weight_decay > 0: grad += weight_decay * W
        m *= b1
        m += (1 - b1) * grad
        v *= b2
        v += (1 - b2) * (grad**2)
        m_hat = m / (1 - b1 + 1e-10)
        v_hat = v / (1 - b2 + 1e-10)
        W -= lr * m_hat / (np.sqrt(v_hat) + eps)

    def softmax(self, x):
        z = x - np.max(x, axis=-1, keepdims=True)
        e_x = np.exp(np.clip(z, -20, 20))
        return e_x / (np.sum(e_x, axis=-1, keepdims=True) + 1e-11)

import numpy as np

class VajraGraphLayer:
    def __init__(self, n_in_experts, dim_in, dim_out, confidence_threshold=0.7):
        self.dim_in = dim_in
        self.dim_out = dim_out
        self.n_experts = n_in_experts
        self.eps = 1e-9

        # 1. HIERARCHICAL WEIGHTS (Xavier/Kaiming Hybrid)
        std = np.sqrt(2.0 / (dim_in + dim_out))
        self.W_experts = (np.random.randn(n_in_experts, dim_in, dim_out) * std).astype(np.float32)

        # Router: symmetry breaking
        self.W_router = (np.random.randn(dim_in, n_in_experts) * 0.01).astype(np.float32)

        # 2. GATED BRIDGE (The Linguistic Highway)
        self.W_bridge = (np.random.randn(dim_in, dim_out) * std).astype(np.float32)

        # 🔱 PAPER SPEC FIX: Lowered from 0.5 to 0.4 to force MoE Expert engagement
        self.bridge_alpha = np.array([0.6], dtype=np.float32)

        # 3. RMSNorm parameters
        self.gamma = np.ones(dim_out, dtype=np.float32)
        self.beta = np.zeros(dim_out, dtype=np.float32)

        # 4. ADAM OPTIMIZER STATES
        self.m_W, self.v_W = np.zeros_like(self.W_experts), np.zeros_like(self.W_experts)
        self.m_R, self.v_R = np.zeros_like(self.W_router), np.zeros_like(self.W_router)
        self.m_B, self.v_B = np.zeros_like(self.W_bridge), np.zeros_like(self.W_bridge)
        self.m_alpha, self.v_alpha = np.zeros_like(self.bridge_alpha), np.zeros_like(self.bridge_alpha)

    def silu(self, x):
        return x * (1.0 / (1.0 + np.exp(-np.clip(x, -20, 20))))

    def rms_norm(self, x):
        rms = np.sqrt(np.mean(x**2, axis=-1, keepdims=True) + self.eps)
        return self.gamma * (x / rms) + self.beta

    def _softmax(self, x):
        z = x - np.max(x, axis=-1, keepdims=True)
        e_x = np.exp(np.clip(z, -20, 20))
        return e_x / (np.sum(e_x, axis=-1, keepdims=True) + 1e-11)

    def forward(self, x, is_training=True):
        if x.ndim == 1:
            x = x.reshape(1, -1)
        batch_size = x.shape[0]

        # --- PHASE 1: ROUTING WITH NOISE JITTER ---
        # 🔱 THE LOAD BALANCER: Adding noise during training to break path collision [21, 7, 4]
        clean_gates = np.dot(x, self.W_router)
        r_noise = np.random.normal(0, 0.1, clean_gates.shape) # 🔱 INCREASED NOISE
        gate_logits = clean_gates + r_noise
        #router_logits = np.dot(x, self.W_router) + r_noise
        gate_probs = self._softmax(gate_logits)

        # --- PHASE 2: EXPERT CONTRACTION ---
        all_expert_outputs = np.einsum('bi,eio->beo', x, self.W_experts)
        activated_experts = self.silu(all_expert_outputs)
        combined_expert_signal = np.einsum('beo,be->bo', activated_experts, gate_probs)

        # --- PHASE 3: GATED BRIDGE ---
        bridge_signal = np.dot(x, self.W_bridge)
        pre_norm = combined_expert_signal + (bridge_signal * self.bridge_alpha)

        output_signal = self.rms_norm(pre_norm)

        cache = {
            "input": x,
            "gate_probs": gate_probs,
            "expert_outputs": all_expert_outputs,
            "activated_experts": activated_experts,
            "bridge_signal": bridge_signal,
            "pre_norm": pre_norm
        }
        return output_signal, cache

    def backward(self, d_out, cache):
        x = cache["input"]
        gate_probs = cache["gate_probs"]
        expert_outputs = cache["expert_outputs"]
        activated_experts = cache["activated_experts"]
        bridge_signal = cache["bridge_signal"]
        batch_size = x.shape[0]

        # 1. RMSNorm Gradient
        pre_norm = cache["pre_norm"].reshape(batch_size, self.dim_out)
        rms = np.sqrt(np.mean(pre_norm**2, axis=-1, keepdims=True) + self.eps)
        d_pre_norm = (d_out * self.gamma / rms).reshape(batch_size, self.dim_out)

        # 2. Expert Path
        d_activated_experts = d_pre_norm[:, np.newaxis, :] * gate_probs[:, :, np.newaxis]
        sig = 1.0 / (1.0 + np.exp(-np.clip(expert_outputs, -20, 20)))
        d_expert_outputs = d_activated_experts * (sig * (1.0 + expert_outputs * (1.0 - sig)))

        d_W_experts = np.zeros_like(self.W_experts)
        for e in range(self.n_experts):
            d_W_experts[e] = np.dot(x.T, d_expert_outputs[:, e, :])

        W_exp_T = self.W_experts.transpose(0, 2, 1)
        d_x_experts = np.sum(np.matmul(d_expert_outputs[:, :, np.newaxis, :], W_exp_T), axis=1).reshape(batch_size, self.dim_in)

        # 3. Router Path
        d_gate_probs = np.sum(activated_experts * d_pre_norm[:, np.newaxis, :], axis=-1)
        d_router_logits = gate_probs * (d_gate_probs - np.sum(gate_probs * d_gate_probs, axis=-1, keepdims=True))
        d_W_router = np.dot(x.T, d_router_logits)
        d_x_router = np.dot(d_router_logits, self.W_router.T)

        # 4. Bridge & Alpha Path
        d_bridge_path = d_pre_norm * self.bridge_alpha
        d_W_bridge = np.dot(x.T, d_bridge_path)
        d_x_bridge = np.dot(d_bridge_path, self.W_bridge.T)

        d_alpha = np.array([np.sum(d_pre_norm * bridge_signal)], dtype=np.float32)

        d_x_total = (d_x_experts + d_x_router + d_x_bridge).reshape(batch_size, self.dim_in)

        return d_x_total, (d_W_experts, d_W_router, d_W_bridge, d_alpha)

"""# Simple NN"""

#/*****/*/
import numpy as np

class VajraBridgeEngine:
    def __init__(self, input_dim=768, topology_config=[96,48,24], vocab_size=15000):

        self.dim = input_dim
        self.config = topology_config
        self.vocab_size = vocab_size
        self.layers = []
        self.token_freq = None

        # ===============================
        # 🔥 DIMENSION FLOW
        # ===============================

        self.dims = [input_dim]

        for i in range(len(topology_config)):
            next_dim = int(self.dims[-1] * 0.6)
            next_dim = max(next_dim, 64)
            self.dims.append(next_dim)

        # ===============================
        # 🔥 BUILD LAYERS
        # ===============================
        for i in range(len(topology_config)):
            self.layers.append(
                VajraGraphLayer(
                    n_in_experts=topology_config[i],
                    dim_in=self.dims[i],
                    dim_out=self.dims[i+1]
                )
            )

        final_dim = self.dims[-1]

        # ===============================
        # 🔥 OUTPUT HEAD
        # ===============================
        self.speech_head = (
            np.random.randn(final_dim, vocab_size) * np.sqrt(1/final_dim)
        ).astype(np.float32)

        self.m_speech = np.zeros_like(self.speech_head)
        self.v_speech = np.zeros_like(self.speech_head)

    # ===============================
    # 🔹 SOFTMAX
    # ===============================
    def softmax(self, x):
        z = x - np.max(x, axis=-1, keepdims=True)
        e_x = np.exp(np.clip(z, -20, 20))
        return e_x / (np.sum(e_x, axis=-1, keepdims=True) + 1e-11)

    # ===============================
    # 🚀 FORWARD
    # ===============================
    def forward(self, x, query_anchor=None, current_pos=0, is_training=True):

        if x.ndim == 1:
            x = x.reshape(1, -1)

        current_signal = x

        caches = []

        for layer in self.layers:
            current_signal, cache = layer.forward(current_signal)
            # current_signal = np.tanh(current_signal) -> COMMENT DOWN 👇
            caches.append(cache)

        word_logits = np.dot(current_signal, self.speech_head)
        word_logits = np.clip(word_logits, -50, 50)

        return word_logits, (caches, current_signal)

    # ===============================
    # 🚀 TRAIN STEP (FIXED)
    # ===============================
    def train_step_raw(self, x_word, q_anchor, target_word_indices):

        batch_size = x_word.shape[0]

        word_logits, (caches, final_out) = self.forward(
            x_word,
            query_anchor=q_anchor,
            is_training=True
        )

        # 🚫 block special tokens
        word_logits[:, [0,1,3]] = -1e9

        probs = self.softmax(word_logits)

        # ===============================
        # 🔥 LABEL SMOOTHING
        # ===============================
        smooth = 0.1
        vocab_size = probs.shape[1]

        target_dist = np.full_like(probs, smooth / vocab_size)

        for b in range(batch_size):
            target = target_word_indices[b]
            target_dist[b, target] += (1.0 - smooth)

        # ===============================
        # 🔥 FREQUENCY-AWARE LOSS
        # ===============================
        loss = 0.0

        for b in range(batch_size):
            target = target_word_indices[b]

            freq = self.token_freq.get(target, 1)
            freq_penalty = 1.0 / (1.0 + np.log1p(freq))

            loss += -freq_penalty * np.sum(
                target_dist[b] * np.log(probs[b] + 1e-10)
            )

        loss /= batch_size

        # ===============================
        # 🔥 GRADIENT
        # ===============================
        d_logits = probs - target_dist
        d_logits /= batch_size

        # ===============================
        # 🔥 BACKPROP HEAD
        # ===============================
        d_speech = np.dot(final_out.T, d_logits)
        d_signal = np.dot(d_logits, self.speech_head.T)

        # ===============================
        # 🔥 BACKPROP LAYERS
        # ===============================
        layer_grads = []

        for i in reversed(range(len(self.layers))):
            d_signal, grads = self.layers[i].backward(d_signal, caches[i])
            layer_grads.append(grads)

        return loss, d_speech, layer_grads[::-1]

    # ===============================
    # 🚀 UPDATE
    # ===============================
    def apply_batch_update(self, d_speech, layer_grads, lr):

        self.apply_adam(self.speech_head, d_speech, self.m_speech, self.v_speech, lr)

        for i, layer in enumerate(self.layers):
            dW, dB, dAlpha = layer_grads[i]

            self.apply_adam(layer.W_experts, dW, layer.m_W, layer.v_W, lr)
            self.apply_adam(layer.W_bridge, dB, layer.m_B, layer.v_B, lr)
            self.apply_adam(layer.bridge_alpha, dAlpha, layer.m_alpha, layer.v_alpha, lr)

    # ===============================
    # 🔹 ADAM
    # ===============================
    def apply_adam(self, W, grad, m, v, lr, b1=0.9, b2=0.999, eps=1e-8):

        grad = np.clip(grad, -1, 1)

        m *= b1
        m += (1 - b1) * grad

        v *= b2
        v += (1 - b2) * (grad ** 2)

        m_hat = m / (1 - b1)
        v_hat = v / (1 - b2)
        W -= lr * m_hat / (np.sqrt(v_hat) + eps)

#/****/
import numpy as np

class VajraGraphLayer:
    def __init__(self, n_in_experts, dim_in, dim_out):
        self.dim_in = dim_in
        self.dim_out = dim_out
        self.n_experts = n_in_experts
        self.eps = 1e-9

        # ===============================
        # 🔥 EXPERT WEIGHTS (NO ROUTER)
        # ===============================
        std = np.sqrt(2.0 / (dim_in + dim_out))
        self.W_experts = (np.random.randn(n_in_experts, dim_in, dim_out) * std).astype(np.float32)

        # ===============================
        # 🔥 BRIDGE
        # ===============================
        self.W_bridge = (np.random.randn(dim_in, dim_out) * std).astype(np.float32)
        self.bridge_alpha = np.array([0.5], dtype=np.float32)

        # ===============================
        # 🔥 NORMALIZATION
        # ===============================
        self.gamma = np.ones(dim_out, dtype=np.float32)
        self.beta = np.zeros(dim_out, dtype=np.float32)

        # ===============================
        # 🔥 OPTIMIZER STATES
        # ===============================
        self.m_W = np.zeros_like(self.W_experts)
        self.v_W = np.zeros_like(self.W_experts)

        self.m_B = np.zeros_like(self.W_bridge)
        self.v_B = np.zeros_like(self.W_bridge)

        self.m_alpha = np.zeros_like(self.bridge_alpha)
        self.v_alpha = np.zeros_like(self.bridge_alpha)

    # ===============================
    # 🔹 ACTIVATION
    # ===============================
    def silu(self, x):
        return x * (1.0 / (1.0 + np.exp(-np.clip(x, -20, 20))))

    # ===============================
    # 🔹 RMS NORM
    # ===============================
    def rms_norm(self, x):
        rms = np.sqrt(np.mean(x**2, axis=-1, keepdims=True) + self.eps)
        return self.gamma * (x / rms) + self.beta

    # ===============================
    # 🚀 FORWARD
    # ===============================
    def forward(self, x, is_training=True):

        if x.ndim == 1:
            x = x.reshape(1, -1)

        # 🔥 EXPERT COMPUTE
        expert_outputs = np.einsum('bi,eio->beo', x, self.W_experts)

        # activation
        activated = self.silu(expert_outputs)

        # average experts
        combined_expert_signal = np.mean(activated, axis=1)

        # 🔥 BRIDGE
        bridge_signal = np.dot(x, self.W_bridge)

        pre_norm = combined_expert_signal + self.bridge_alpha * bridge_signal

        output = self.rms_norm(pre_norm)

        cache = {
            "input": x,
            "expert_outputs": expert_outputs,
            "activated": activated,
            "bridge_signal": bridge_signal,
            "pre_norm": pre_norm
        }

        return output, cache

    # ===============================
    # 🔙 BACKWARD (FULLY FIXED)
    # ===============================
    def backward(self, d_out, cache):

        x = cache["input"]                        # (B, dim_in)
        expert_outputs = cache["expert_outputs"]  # (B, E, dim_out)
        bridge_signal = cache["bridge_signal"]

        # ===============================
        # 🔥 RMS NORM BACKWARD
        # ===============================
        pre_norm = cache["pre_norm"]
        rms = np.sqrt(np.mean(pre_norm**2, axis=-1, keepdims=True) + self.eps)
        d_pre = d_out * self.gamma / rms          # (B, dim_out)
        d_pre -= (pre_norm * np.mean(d_out * pre_norm, axis=-1, keepdims=True)) / (rms**3 + self.eps)
        # ===============================
        # 🔥 EXPERT PATH
        # ===============================
        d_W_experts = np.zeros_like(self.W_experts)

        sig = 1.0 / (1.0 + np.exp(-np.clip(expert_outputs, -20, 20)))

        d_x = np.zeros_like(x)

        for e in range(self.n_experts):

            exp_out = expert_outputs[:, e, :]     # (B, dim_out)

            d_act = d_pre / self.n_experts        # distribute

            # SiLU derivative
            d_exp = d_act * (sig[:, e, :] * (1 + exp_out * (1 - sig[:, e, :])))

            # weight gradient
            d_W_experts[e] = np.dot(x.T, d_exp) / (x.shape[0] + 1e-9)

            # input gradient (CORRECT)
            d_x += np.dot(d_exp, self.W_experts[e].T)

        # ===============================
        # 🔥 BRIDGE PATH
        # ===============================
        d_bridge = d_pre * self.bridge_alpha
        d_W_bridge = np.dot(x.T, d_bridge) / (x.shape[0] + 1e-9)

        d_alpha = np.array([np.sum(d_pre * bridge_signal)], dtype=np.float32)

        # add bridge input grad
        d_x += np.dot(d_bridge, self.W_bridge.T)

        return d_x, (d_W_experts, d_W_bridge, d_alpha)

"""# Data Engineering"""

import json
from datasets import load_dataset
from collections import Counter
import numpy as np


class VajraStage1Inspector:

    def __init__(self, jsonl_path, raw_json_path):
        self.jsonl_path = jsonl_path
        self.raw_json_path = raw_json_path

    # ===============================
    # 🔹 LOAD DOMAIN JSONL
    # ===============================
    def load_domain(self):
        data = []

        print("🛰️ Loading DOMAIN JSONL...")

        try:
            with open(self.jsonl_path, "r") as f:
                for line in f:

                    if not line.strip():
                        continue

                    try:
                        entry = json.loads(line)
                    except:
                        continue

                    q = str(
                        entry.get("instruction") or
                        entry.get("query") or
                        entry.get("input") or ""
                    )

                    r = str(
                        entry.get("response") or
                        entry.get("output") or
                        entry.get("text") or ""
                    )

                    if len(q.strip()) > 3 and len(r.strip()) > 5:
                        data.append({
                            "query": q.strip(),
                            "response": r.strip(),
                            "source": "domain"
                        })

        except Exception as e:
            print(f"❌ Failed to load domain JSONL: {e}")
            return []

        print(f"✅ Domain Loaded: {len(data)}")
        return data

    # ===============================
    # 🔹 LOAD RAW PDF JSON
    # ===============================
    def load_raw_pdf(self):
        data = []

        print("🛰️ Loading RAW PDF JSON...")

        try:
            with open(self.raw_json_path, "r") as f:
                pages = json.load(f)
        except Exception as e:
            print(f"❌ JSON LOAD FAILED: {e}")
            return []

        if isinstance(pages, dict):
            pages = pages.get("pages", [])

        if not isinstance(pages, list):
            print("❌ Unknown JSON format")
            return []

        for page in pages:

            text = ""

            if isinstance(page, dict):
                text = page.get("text", "")
            elif isinstance(page, str):
                text = page

            text = str(text).strip()

            # 🔥 HARD FILTER (NO ML)
            if len(text) < 30:
                continue

            if any(bad in text.lower() for bad in [
                "equation", "figure", "table", "annexure"
            ]):
                continue

            data.append({
                "query": "extract groundwater information",
                "response": text,
                "source": "raw_pdf"
            })

        print(f"✅ Raw PDF Loaded: {len(data)}")

        # DEBUG
        print("\n🔍 RAW SAMPLE CHECK:")
        for i in range(min(3, len(data))):
            print(f"--- RAW {i+1} ---")
            print(data[i]["response"][:200])
            print()

        return data

    # ===============================
    # 🔹 LOAD DOLLY
    # ===============================
    def load_dolly(self, limit=300):
        data = []

        print("🛰️ Loading DOLLY...")

        try:
            dataset = load_dataset("databricks/databricks-dolly-15k", split="train")
        except Exception as e:
            print(f"❌ Failed to load Dolly: {e}")
            return []

        for d in dataset:

            q = str(d.get("instruction", ""))
            r = str(d.get("response", ""))

            if len(q.strip()) > 3 and len(r.strip()) > 5:
                data.append({
                    "query": q.strip(),
                    "response": r.strip(),
                    "source": "dolly"
                })

            if len(data) >= limit:
                break

        print(f"✅ Dolly Loaded: {len(data)}")
        return data

    # ===============================
    # 🔍 INSPECTION
    # ===============================
    def inspect(self, dataset):

        if not dataset:
            print("❌ No data available")
            return

        print("\n🔍 ===============================")
        print("🔱 STAGE 1 DATA INSPECTION")
        print("=================================\n")

        print(f"📊 TOTAL SAMPLES: {len(dataset)}\n")

        print("🧾 SAMPLE DATA\n")
        for i in range(min(5, len(dataset))):
            item = dataset[i]
            print(f"--- SAMPLE {i+1} ({item['source']}) ---")
            print("Q:", item["query"][:150])
            print("R:", item["response"][:200])
            print()

        lengths = [len(item["response"].split()) for item in dataset]

        print("📊 LENGTH STATS")
        print(f"Avg Length : {np.mean(lengths):.2f}")
        print(f"Max Length : {np.max(lengths)}")
        print(f"Min Length : {np.min(lengths)}")

        token_counter = Counter()

        for item in dataset[:1000]:
            tokens = item["response"].lower().split()
            token_counter.update(tokens)

        print("\n🔥 TOP WORDS")
        for w, c in token_counter.most_common(20):
            print(f"{w} → {c}")

        domain_words = ["groundwater", "aquifer", "recharge", "district", "state"]

        hits = 0
        for item in dataset[:500]:
            if any(k in item["response"].lower() for k in domain_words):
                hits += 1

        print("\n🎯 DOMAIN PRESENCE")
        print(f"{hits}/500 samples contain domain keywords")

        source_counter = Counter([d["source"] for d in dataset])

        print("\n📊 SOURCE DISTRIBUTION")
        for k, v in source_counter.items():
            print(f"{k}: {v}")

    # ===============================
    # 🚀 RUN
    # ===============================
    def run(self):

        domain = self.load_domain()
        raw = self.load_raw_pdf()
        dolly = self.load_dolly()

        full_dataset = domain + raw + dolly

        if len(full_dataset) == 0:
            print("❌ CRITICAL: No data loaded!")
            return []

        # ❌ NO EMBEDDING HERE (IMPORTANT FIX)

        self.inspect(full_dataset)

        return full_dataset


# ===============================
# 🚀 EXECUTION
# ===============================
inspector = VajraStage1Inspector(
    jsonl_path="VAJRA_INTELLIGENCE.jsonl",
    raw_json_path="gov_of_india_2024.json"
)

stage1_dataset = inspector.run()

import random
import re

class VajraStage2Builder:

    def __init__(self, dataset):
        self.dataset = dataset

        # 🔥 VALID STATES
        self.valid_states = set([
            "andhra", "arunachal", "assam", "bihar", "chhattisgarh",
            "goa", "gujarat", "haryana", "himachal", "jharkhand",
            "karnataka", "kerala", "madhya", "maharashtra", "manipur",
            "meghalaya", "mizoram", "nagaland", "odisha", "punjab",
            "rajasthan", "sikkim", "tamil", "telangana", "tripura",
            "uttar", "uttarakhand", "west", "delhi", "jammu", "ladakh"
        ])

    # ===============================
    # 🔹 CLEAN TEXT
    # ===============================
    def clean_text(self, text):
        text = str(text).lower()
        text = " ".join(text.split())

        text = text.replace("percent", "%")
        text = text.replace("billion cubic meters", "bcm")
        text = text.replace("over exploited", "over-exploited")

        text = re.sub(r'(\d+)\s*\.\s*(\d+)', r'\1.\2', text)

        return text

    # ===============================
    # 🔥 SENTENCE SPLIT
    # ===============================
    def split_sentences(self, text):
        sentences = re.split(r'[.?!]', text)
        return [s.strip() for s in sentences if len(s.strip().split()) >= 5]

    # ===============================
    # 🔥 STRUCTURE FROM DOMAIN (KEY FIX)
    # ===============================
    def extract_structured_from_domain(self, text):

        structured = []
        text = text.lower()

        matches = re.findall(
            r'(\w+)\s+in\s+(\w+)\s+contains.*?(safe|critical|semi-critical|over-exploited)',
            text
        )

        for district, state, category in matches:

            if state not in self.valid_states:
                continue

            if len(district) < 3:
                continue

            structured.append({
                "query": f"groundwater status of {district} in {state}",
                "response": f"{district} in {state} contains units classified as {category}",
                "expert_tag": "structured"
            })

        return structured

    # ===============================
    # 🔹 QUERY REWRITE
    # ===============================
    def rewrite_query(self, query, response):

        words = response.split()

        for i in range(len(words) - 2):
            if words[i+1] == "in":
                return f"groundwater status of {words[i]} in {words[i+2]}"

        return "groundwater classification based on extraction"

    # ===============================
    # 🔹 LENGTH FILTER
    # ===============================
    def valid_length(self, text):
        l = len(text.split())
        return 5 <= l <= 120

    # ===============================
    # 🔥 NOISE FILTER
    # ===============================
    def is_noise(self, text):
        bad = [
            "equation", "formula", "figure", "table",
            "annexure", "model", "graph",
            "rainfall recharge", "methodology"
        ]
        return any(b in text for b in bad)

    # ===============================
    # 🔥 PROCESS RAW PDF (NO STRUCTURE HERE)
    # ===============================
    def process_raw_pdf(self, query, response):

        samples = []
        sentences = self.split_sentences(response)

        for i in range(len(sentences)):

            chunk = sentences[i]

            if i + 1 < len(sentences) and random.random() > 0.5:
                chunk += ". " + sentences[i+1]

            if not self.valid_length(chunk):
                continue

            if self.is_noise(chunk):
                continue

            samples.append({
                "query": self.rewrite_query(query, chunk),
                "response": chunk,
                "expert_tag": "raw_pdf"
            })

        return samples

    # ===============================
    # 🔹 BALANCE
    # ===============================
    def balance(self, domain, raw, dolly):

        structured = [d for d in raw if d["expert_tag"] == "structured"]
        normal_raw = [d for d in raw if d["expert_tag"] != "structured"]

        structured = structured[:1000]
        normal_raw = normal_raw[:500]

        raw = structured + normal_raw

        domain = domain[:1500]
        dolly = dolly[:200]

        final = domain + raw + dolly
        random.shuffle(final)

        print("\n📊 BALANCED DATASET")
        print(f"Domain       : {len(domain)}")
        print(f"Structured   : {len(structured)}")
        print(f"Raw Normal   : {len(normal_raw)}")
        print(f"Dolly        : {len(dolly)}")
        print(f"Total        : {len(final)}")

        return final

    # ===============================
    # 🚀 BUILD (UPDATED)
    # ===============================
    def build(self):

        print("\n🔱 STAGE 2: CLEAN + STRUCTURE + BALANCE\n")

        domain_data, raw_data, dolly_data = [], [], []

        for item in self.dataset:

            try:
                q = self.clean_text(item["query"])
                r = self.clean_text(item["response"])
                source = item["source"]
            except:
                continue

            if not q or not r:
                continue

            if source == "raw_pdf":
                raw_data.extend(self.process_raw_pdf(q, r))

            elif source == "domain":

                # 🔥 NORMAL DOMAIN SAMPLE
                if self.valid_length(r):
                    domain_data.append({
                        "query": self.rewrite_query(q, r),
                        "response": r,
                        "expert_tag": "domain"
                    })

                # 🔥 STRUCTURED EXTRACTION (KEY PART)
                structured_samples = self.extract_structured_from_domain(r)

                for s in structured_samples:
                    raw_data.extend([s] * 3)   # boost

            else:
                if self.valid_length(r):
                    dolly_data.append({
                        "query": self.rewrite_query(q, r),
                        "response": r,
                        "expert_tag": "dolly"
                    })

        final_dataset = self.balance(domain_data, raw_data, dolly_data)

        return final_dataset


# ===============================
# 🚀 EXECUTION
# ===============================

stage2_builder = VajraStage2Builder(stage1_dataset)
stage2_dataset = stage2_builder.build()

print(f"\n✅ Stage 2 Dataset Ready: {len(stage2_dataset)} samples")

from collections import defaultdict, Counter
import re

def build_geo_graph(dataset):

    district_state_counter = defaultdict(Counter)

    for item in dataset:

        if item["expert_tag"] != "structured":
            continue

        text = item["response"]

        match = re.search(r'(\w+)\s+in\s+(\w+)', text)

        if match:
            district, state = match.groups()
            district_state_counter[district][state] += 1

    # ===============================
    # 🔥 FINAL MAPPING
    # ===============================
    district_to_state = {}
    state_to_districts = defaultdict(list)

    for district, states in district_state_counter.items():

        best_state = states.most_common(1)[0][0]

        district_to_state[district] = best_state
        state_to_districts[best_state].append(district)

    print(f"✅ Districts mapped: {len(district_to_state)}")

    return district_to_state, state_to_districts

def clean_geo_graph(district_to_state):

    cleaned = {}

    BAD_DISTRICTS = {
        "east", "west", "north", "south",
        "hills", "water", "units", "area",
        "level", "kannada", "sahib"
    }

    for d, s in district_to_state.items():

        # ❌ remove garbage
        if d in BAD_DISTRICTS:
            continue

        # ❌ remove underscore noise
        if "_" in d:
            continue

        # ❌ remove very short tokens
        if len(d) < 3:
            continue

        # ❌ remove numeric
        if any(c.isdigit() for c in d):
            continue

        cleaned[d] = s

    return cleaned

def build_fact_db(dataset):

    import re

    fact_db = {}

    for item in dataset:

        text = item["response"].lower()

        # 🔥 STRICT NUMBER FILTER (avoid %)
        match = re.search(
            r'(\w+)\s+in\s+(\w+).*?(\d{2,}\.\d+)\s+units.*?(safe|critical|semi-critical|over-exploited)',
            text
        )

        if match:
            district, state, units, category = match.groups()

            fact_db[district] = {
                "state": state,
                "units": units,
                "category": category
            }

    return fact_db

district_to_state, state_to_districts = build_geo_graph(stage2_dataset)

district_to_state = clean_geo_graph(district_to_state)

fact_db = build_fact_db(stage2_dataset)

print(fact_db.get("mandya"))

from sklearn.model_selection import train_test_split

train_dataset, test_dataset = train_test_split(
    stage2_dataset,
    test_size=0.2,
    random_state=42
)

print("Train:", len(train_dataset))
print("Test :", len(test_dataset))

import re
from collections import Counter

class VajraVocab:
    def __init__(self, max_vocab=6000):   # 🔥 INCREASED
        self.max_vocab = max_vocab

        # 🔹 Special tokens
        self.word2idx = {
            "<PAD>": 0,
            "<SOS>": 1,
            "<EOS>": 2,
            "<UNK>": 3
        }

        self.idx2word = {v: k for k, v in self.word2idx.items()}
        self.n_words = 4

        # 🔥 IMPORTANT: core grammar words (never lost)
        self.structural_glue = [
            "the", "is", "of", "and", "in", "to", "with",
            "are", "was", "were", "a", "an", "on",
            "per", "according", "based", "indicates",
            "shows", "represents", "contains"
        ]

        # 🔥 IMPORTANT: domain keywords (force include)
        self.domain_words = [
            "groundwater", "aquifer", "extraction", "recharge",
            "availability", "district", "state", "india",
            "safe", "critical", "overexploited", "units",
            "classification", "assessment", "annual", "national"
        ]

        # add them first
        for w in self.structural_glue + self.domain_words:
            self._add_word(w)

    # ===============================
    # 🔹 ADD WORD
    # ===============================
    def _add_word(self, word):
        if word not in self.word2idx and self.n_words < self.max_vocab:
            self.word2idx[word] = self.n_words
            self.idx2word[self.n_words] = word
            self.n_words += 1

    # ===============================
    # 🔹 CLEAN TEXT (SAFE)
    # ===============================
    def clean_text(self, text):
        text = str(text).lower()
        text = " ".join(text.split())

        text = text.replace("percent", "%")
        text = text.replace("billion cubic meters", "bcm")

        text = re.sub(r'(\d+)\s*\.\s*(\d+)', r'\1.\2', text)

        # 🔥 IMPORTANT: KEEP NUMBERS + WORDS
        text = re.sub(r'[^a-z0-9\%\.\-\s]', ' ', text)

        return " ".join(text.split())

    # ===============================
    # 🔥 BUILD VOCAB (FIXED 🔥)
    # ===============================
    def build(self, dataset):

        print("📡 BUILDING VOCAB (STAGE 3)...")

        token_counter = Counter()

        # 🔹 collect ALL tokens
        for item in dataset:
            combined = item["query"] + " " + item["response"]
            tokens = self.clean_text(combined).split()
            token_counter.update(tokens)

        print(f"🔢 Unique tokens found: {len(token_counter)}")

        # 🔥 SORT BY FREQUENCY
        sorted_tokens = sorted(
            token_counter.items(),
            key=lambda x: x[1],
            reverse=True
        )

        # 🔥 KEEP EVEN RARE WORDS (VERY IMPORTANT)
        for word, freq in sorted_tokens:

            # ❌ DO NOT DROP freq=1 words
            # only skip garbage
            if len(word) <= 1:
                continue

            self._add_word(word)

        print(f"✅ Final Vocab Size: {self.n_words}")

    # ===============================
    # 🔹 STATS
    # ===============================
    def stats(self):
        print("\n📊 VOCAB STATS")
        print(f"Total Words: {self.n_words}")

        # sample domain words check
        sample_check = ["mandya", "karnataka", "tonk", "cuttack"]

        print("\n🔍 DOMAIN WORD CHECK:")
        for w in sample_check:
            print(f"{w}: {'✅' if w in self.word2idx else '❌'}")

vocab = VajraVocab(max_vocab=6000)
vocab.build(stage2_dataset)
vocab.stats()

from sentence_transformers import SentenceTransformer
import numpy as np

class VajraEmbedder:

    def __init__(self, vocab):
        print("🚀 Loading embedding model...")

        self.model = SentenceTransformer('all-MiniLM-L6-v2')
        self.dim = 384
        self.vocab = vocab

        self.embedding_matrix = None
        self.build_embedding_matrix()

    # ===============================
    # 🔹 BUILD VOCAB EMBEDDINGS
    # ===============================
    def build_embedding_matrix(self):

        print("🛰️ Building embedding matrix...")

        words = [self.vocab.idx2word[i] for i in range(self.vocab.n_words)]

        vectors = self.model.encode(
            words,
            batch_size=64,
            show_progress_bar=True,
            convert_to_numpy=True
        )

        # normalize (IMPORTANT)
        norms = np.linalg.norm(vectors, axis=1, keepdims=True) + 1e-9
        vectors = vectors / norms

        self.embedding_matrix = vectors.astype(np.float32)

        print(f"✅ Embedding matrix ready: {self.embedding_matrix.shape}")

    # ===============================
    # 🔹 ENCODE QUERY
    # ===============================
    def encode(self, text):

        if not text or not text.strip():
            return np.zeros(self.dim, dtype=np.float32)

        vec = self.model.encode(text, convert_to_numpy=True)

        norm = np.linalg.norm(vec) + 1e-9
        vec = vec / norm

        return vec.astype(np.float32)

import numpy as np

def finalize_and_vectorize(dataset, vocab, embedder):

    print(f"🧬 VECTORIZING {len(dataset)} SAMPLES...")
    final_data = []

    total_unk = 0
    total_tokens = 0

    for item in dataset:

        # ===============================
        # 🔹 BASIC VALIDATION
        # ===============================
        if not item["query"] or not item["response"]:
            continue

        # ===============================
        # 🔹 CLEAN TEXT
        # ===============================
        clean_res = vocab.clean_text(item["response"])
        tokens = clean_res.split()

        if len(tokens) < 4:
            continue

        tokens = tokens[:30]   # 🔥 control length

        # ===============================
        # 🔹 ENCODE QUERY (FAST + SAFE)
        # ===============================
        query_vec = embedder.encode(item["query"])

        # ===============================
        # 🔹 STYLE BIAS (OPTIONAL)
        # ===============================
        style_bias = np.zeros(384, dtype=np.float32)

        if item["expert_tag"] == "prof_comm":
            style_bias[2] = 0.02
        else:
            style_bias[3] = 0.02

        query_vector = query_vec + style_bias

        # ===============================
        # 🔹 TOKEN → INDEX
        # ===============================
        response_indices = [1]   # <SOS>

        unk_count = 0
        valid_tokens = 0

        for w in tokens:

            idx_w = vocab.word2idx.get(w, 3)

            if idx_w == 3:
                unk_count += 1

            response_indices.append(idx_w)
            valid_tokens += 1

        response_indices.append(2)  # <EOS>

        # ===============================
        # 🔥 RELAXED FILTER (IMPORTANT)
        # ===============================
        if valid_tokens < 4:
            continue

        # 🔥 ONLY DROP IF COMPLETELY BROKEN
        if unk_count > len(tokens) * 0.9:
            continue

        if len(response_indices) < 6:
            continue

        # ===============================
        # 🔹 TRACK UNK STATS
        # ===============================
        total_unk += unk_count
        total_tokens += len(tokens)

        # ===============================
        # 🔹 ADD SAMPLE
        # ===============================
        final_data.append({
            "query_vector": query_vector.astype(np.float32),
            "response_indices": response_indices,
            "expert_tag": item["expert_tag"]
        })

    # ===============================
    # 📊 FINAL STATS
    # ===============================
    unk_ratio = total_unk / (total_tokens + 1e-9)

    print(f"✅ Final Samples: {len(final_data)}")
    print(f"📊 UNK Ratio: {unk_ratio:.3f}")

    return final_data

embedder = VajraEmbedder(vocab)

train_manifold = finalize_and_vectorize(
    train_dataset,
    vocab,
    embedder
)

test_manifold = finalize_and_vectorize(
    test_dataset,
    vocab,
    embedder
)

def vajra_audit(vocab, dataset, train_data, embedder):

    import numpy as np
    import random

    print("\n🔍 ===============================")
    print("🔱 VAJRA LIGHT AUDIT")
    print("=================================\n")

    # ===============================
    # 📊 BASIC STATS
    # ===============================
    print("📊 DATA OVERVIEW\n")
    print(f"Raw Dataset       : {len(dataset)}")
    print(f"Training Samples  : {len(train_data)}")

    # ===============================
    # 🧾 SHOW WHAT MODEL SEES (IMPORTANT)
    # ===============================
    print("\n🧾 MODEL INPUT SAMPLES\n")

    for i in range(3):
        sample = random.choice(train_data)

        words = [vocab.idx2word.get(t, "<UNK>") for t in sample["response_indices"]]
        text = " ".join(words)

        print(f"--- SAMPLE {i+1} ---")
        print(text[:200])
        print()

    # ===============================
    # 📊 LENGTH ANALYSIS
    # ===============================
    print("\n📊 SEQUENCE STATS\n")

    lengths = [
        len(s["response_indices"])
        for s in train_data
    ]

    print(f"Avg Length : {np.mean(lengths):.2f}")
    print(f"Max Length : {np.max(lengths)}")
    print(f"Min Length : {np.min(lengths)}")

    # ===============================
    # 🎯 DOMAIN SIGNAL
    # ===============================
    print("\n🎯 DOMAIN PRESENCE\n")

    domain_keywords = [
        "groundwater", "aquifer", "extraction",
        "recharge", "availability", "classification",
        "units", "state", "district", "india"
    ]

    hits = 0

    for sample in train_data[:300]:
        words = [vocab.idx2word.get(t, "") for t in sample["response_indices"]]
        text = " ".join(words)

        if any(k in text for k in domain_keywords):
            hits += 1

    print(f"Domain Coverage: {hits}/300")

    # ===============================
    # 🔁 TOKEN REPETITION
    # ===============================
    print("\n🔁 REPETITION CHECK\n")

    repeated = 0

    for sample in train_data[:300]:
        tokens = sample["response_indices"]

        if len(tokens) > 6:
            if tokens[-3:] == tokens[-6:-3]:
                repeated += 1

    print(f"Loop Patterns: {repeated}/300")

    # ===============================
    # 🧠 SEMANTIC ALIGNMENT
    # ===============================
    print("\n🧠 QUERY ↔ RESPONSE ALIGNMENT\n")

    sims = []

    for sample in train_data[:100]:
        words = [vocab.idx2word.get(t, "") for t in sample["response_indices"]]
        text = " ".join(words)

        vec = embedder.encode(text)
        q_vec = sample["query_vector"]

        sim = np.dot(vec, q_vec) / (
            np.linalg.norm(vec) * np.linalg.norm(q_vec) + 1e-9
        )

        sims.append(sim)

    print(f"Avg Cosine Similarity: {np.mean(sims):.3f}")

    # ===============================
    # 🧠 DIVERSITY
    # ===============================
    print("\n🧠 DIVERSITY\n")

    unique = set()

    for sample in train_data[:300]:
        words = [vocab.idx2word.get(t, "") for t in sample["response_indices"]]
        unique.add(" ".join(words))

    print(f"Unique Sentences: {len(unique)}/300")

    # ===============================
    # 🧠 FINAL VERDICT
    # ===============================
    print("\n🧠 FINAL VERDICT\n")

    if len(train_data) < 1000:
        print("❌ TOO SMALL")

    if hits < 150:
        print("❌ WEAK DOMAIN")

    if np.mean(sims) < 0.2:
        print("❌ POOR QUERY ALIGNMENT")

    if repeated > 50:
        print("❌ REPETITION RISK")

    print("\n✅ READY FOR TRAINING IF NO ❌")

vajra_audit(
    vocab,
    train_dataset,
    train_manifold,
    embedder
)

for w in ["mandya", "karnataka", "pune", "maharashtra"]:
    print(w, "→", w in vocab.word2idx)

print(district_to_state.get("mandya"))
print(district_to_state.get("pune"))

for i in range(3):
    sample = random.choice(train_manifold)
    words = [vocab.idx2word[t] for t in sample["response_indices"]]
    print(" ".join(words))

"""# Initialisation"""

# --- 🔱 VAJRA TEST INITIALIZATION ---
import numpy as np

print("🔱 MODE: FAST DEBUG TRAINING (500 SAMPLES)")

# ===============================
# 🔥 SMALL DATA SUBSET
# ===============================
TEST_SIZE = 500

# shuffle for randomness
np.random.shuffle(train_manifold)

active_train_data = train_manifold[:TEST_SIZE]

# ===============================
# 🔥 SMALL MODEL (FAST LEARNING)
# ===============================
topology = [32, 16, 8]   # fast + stable for debugging

# ===============================
# 🚀 ENGINE (CLEAN VERSION)
# ===============================
engine = VajraBridgeEngine(
    input_dim=768,
    topology_config=topology,
    vocab_size=len(vocab.word2idx)
)

# ===============================
# 🔍 SANITY CHECK
# ===============================
print("\n🔍 ENGINE CHECK")
print("Speech head shape:", engine.speech_head.shape)

# ===============================
# 📊 INFO
# ===============================
print(f"\n✅ VAJRA ENGINE INITIALIZED (TEST MODE)")
print(f"📍 Topology: {' -> '.join(map(str, topology))}")
print(f"📍 Training Dataset: {len(active_train_data)} samples")
print(f"⚡ STATUS: CLEAN DEBUG MODE READY")

def positional_encoding(pos, dim):
    pe = np.zeros(dim)
    for i in range(0, dim, 2):
        pe[i] = np.sin(pos / (10000 ** (i / dim)))
        if i+1 < dim:
            pe[i+1] = np.cos(pos / (10000 ** (i / dim)))
    return pe

"""#Training"""

#/***/
import numpy as np
from tqdm import tqdm
import random
from collections import Counter

# ===============================
# 🔱 CONFIG
# ===============================
EPOCHS = 2
LR = 1e-3

MAX_TOKENS = 25
STEP_SKIP = 1
ACCUM_STEPS = 4

QUERY_SCALE = 1.5     # 🔥 important
POS_SCALE = 0.1       # 🔥 positional strength

print("🚀 VAJRA CLEAN TRAINING STARTED")

embedding_matrix = embedder.embedding_matrix
EMB_DIM = embedding_matrix.shape[1]

# ===============================
# 🔥 POSITIONAL ENCODING
# ===============================
def positional_encoding(pos, dim):
    pe = np.zeros(dim, dtype=np.float32)
    for i in range(0, dim, 2):
        pe[i] = np.sin(pos / (10000 ** (i / dim)))
        if i + 1 < dim:
            pe[i + 1] = np.cos(pos / (10000 ** (i / dim)))
    return pe

# ===============================
# 🔥 TOKEN FREQUENCY
# ===============================
print("🧠 Building token frequencies...")

token_counter = Counter()
for sample in active_train_data:
    token_counter.update(sample['response_indices'])

engine.token_freq = token_counter

# ===============================
# 🔥 SIMPLE BLEU
# ===============================
def simple_bleu(pred_tokens, target_tokens):
    pred_set = set(pred_tokens)
    target_set = set(target_tokens)
    return len(pred_set & target_set) / (len(target_set) + 1e-9)

# ===============================
# 🔥 QUICK GENERATION (UPDATED)
# ===============================
def quick_generate(sample):

    query_vec = sample['query_vector']
    query_vec = query_vec / (np.linalg.norm(query_vec) + 1e-9)

    current_token = 1
    generated = []

    context = np.zeros(EMB_DIM, dtype=np.float32)

    for pos in range(15):

        curr_emb = embedding_matrix[current_token]

        # 🔥 CONTEXT UPDATE WITH QUERY
        context = 0.4 * context + 0.5 * curr_emb + 0.1 * query_vec

        # 🔥 POSITIONAL ADD
        context += POS_SCALE * positional_encoding(pos, EMB_DIM)

        # 🔥 NORMALIZE
        context = context / (np.linalg.norm(context) + 1e-9)

        x_word = np.concatenate([
            context,
            QUERY_SCALE * query_vec
        ]).reshape(1, -1)

        logits, _ = engine.forward(
            x_word,
            query_anchor=query_vec,
            current_pos=pos,
            is_training=False
        )

        probs = engine.softmax(logits)

        # 🚫 block special tokens
        probs[0][0] = probs[0][1] = probs[0][3] = 0

        # 🔥 SAFE NORMALIZATION
        probs = np.clip(probs, 0, None)
        s = np.sum(probs)

        if s <= 1e-12 or np.isnan(s):
            probs = np.ones_like(probs)
            probs /= np.sum(probs)
        else:
            probs /= s

        probs = probs / np.sum(probs)

        next_token = np.random.choice(len(probs[0]), p=probs[0])

        if next_token == 2:
            break

        generated.append(next_token)
        current_token = next_token

    return generated

# ===============================
# 🚀 TRAIN LOOP
# ===============================
for epoch in range(EPOCHS):
    print(f"\n🔁 Epoch {epoch+1}/{EPOCHS}")

    total_loss = 0
    step_count = 0
    unk_count = 0
    total_tokens = 0

    np.random.shuffle(active_train_data)

    acc_d_speech = np.zeros_like(engine.speech_head)
    acc_layer_grads = None

    progress_bar = tqdm(active_train_data, ncols=100)

    eval_points = set([
        int(len(active_train_data) * x)
        for x in [0.2, 0.4, 0.6, 0.8]
    ])

    for i, sample in enumerate(progress_bar):

        query_anchor = sample['query_vector']
        query_anchor = query_anchor / (np.linalg.norm(query_anchor) + 1e-9)

        tokens = sample['response_indices'][:MAX_TOKENS]

        if len(tokens) < 3:
            continue

        sample_d_speech = np.zeros_like(engine.speech_head)
        sample_layer_grads = None

        context = np.zeros(EMB_DIM, dtype=np.float32)

        for t in range(0, len(tokens) - 1, STEP_SKIP):

            token_id = tokens[t]
            target_word = tokens[t + 1]

            total_tokens += 1
            if token_id == 3:
                unk_count += 1

            curr_emb = embedding_matrix[token_id]

            # ===============================
            # 🔥 CONTEXT UPDATE (KEY FIX)
            # ===============================
            context = 0.4 * context + 0.5 * curr_emb + 0.1 * query_anchor

            # 🔥 POSITIONAL SIGNAL
            context += POS_SCALE * positional_encoding(t, EMB_DIM)

            # 🔥 NORMALIZE
            context = context / (np.linalg.norm(context) + 1e-9)

            # ===============================
            # 🔥 FINAL INPUT
            # ===============================
            x_word = np.concatenate([
                context,
                QUERY_SCALE * query_anchor
            ]).reshape(1, -1)

            loss, d_speech, layer_grads = engine.train_step_raw(
                x_word,
                q_anchor=query_anchor,
                target_word_indices=np.array([target_word])
            )

            total_loss += loss
            step_count += 1

            sample_d_speech += d_speech

            if sample_layer_grads is None:
                sample_layer_grads = [
                    [g.copy() for g in layer]
                    for layer in layer_grads
                ]
            else:
                for l in range(len(layer_grads)):
                    for g in range(len(layer_grads[l])):
                        sample_layer_grads[l][g] += layer_grads[l][g]

        if sample_layer_grads is None:
            continue

        acc_d_speech += sample_d_speech

        if acc_layer_grads is None:
            acc_layer_grads = sample_layer_grads
        else:
            for l in range(len(sample_layer_grads)):
                for g in range(len(sample_layer_grads[l])):
                    acc_layer_grads[l][g] += sample_layer_grads[l][g]

        # ===============================
        # 🔥 APPLY UPDATE
        # ===============================
        if (i + 1) % ACCUM_STEPS == 0:

            np.clip(acc_d_speech, -1, 1, out=acc_d_speech)

            engine.apply_batch_update(
                acc_d_speech,
                acc_layer_grads,
                lr=LR
            )

            acc_d_speech.fill(0)
            acc_layer_grads = None

        # ===============================
        # 📊 LIVE LOSS
        # ===============================
        if step_count > 0 and i % 20 == 0:
            progress_bar.set_postfix(loss=total_loss / step_count)

        # ===============================
        # 🧠 EVALUATION
        # ===============================
        if i in eval_points:

            print(f"\n\n🔍 EVALUATION @ {int((i/len(active_train_data))*100)}%")

            sample_eval = random.choice(active_train_data)

            pred = quick_generate(sample_eval)
            target = sample_eval['response_indices']

            bleu = simple_bleu(pred, target)

            pred_words = [vocab.idx2word.get(t, "<UNK>") for t in pred]
            target_words = [vocab.idx2word.get(t, "<UNK>") for t in target]

            print("\n🧠 PREDICTED:")
            print(" ".join(pred_words[:20]))

            print("\n🎯 TARGET:")
            print(" ".join(target_words[:20]))

            print(f"\n📊 BLEU (approx): {bleu:.4f}")

    # ===============================
    # 🔥 FINAL UPDATE
    # ===============================
    if acc_layer_grads is not None:
        engine.apply_batch_update(
            acc_d_speech,
            acc_layer_grads,
            lr=LR
        )

    avg_loss = total_loss / (step_count + 1e-9)
    unk_ratio = unk_count / (total_tokens + 1e-9)

    print(f"\n📉 Epoch {epoch+1} Loss: {avg_loss:.4f}")
    print(f"🧠 UNK Ratio: {unk_ratio:.4f}")

print("\n✅ TRAINING COMPLETE")

"""#Testing"""

import numpy as np
import random

def vajra_generate_v4(engine, embedder, vocab, query,
                     district_to_state,
                     fact_db,
                     max_len=25,
                     temperature=0.8,
                     top_k=8,
                     num_candidates=4):

    print("\n🧠 VAJRA V4 — GEO + FACT GROUNDED GENERATION\n")

    embedding_matrix = embedder.embedding_matrix
    query_vec = embedder.encode(query)

    eos_token = 2
    special_block = {0, 1, 3}

    # ===============================
    # 🔥 DETECT DISTRICT
    # ===============================
    query_words = query.lower().split()

    detected_district = None
    detected_state = None

    for w in query_words:
        if w in district_to_state:
            detected_district = w
            detected_state = district_to_state[w]
            break

    if detected_district:
        print(f"📍 Detected: {detected_district} → {detected_state}")

    all_candidates = []
    scores = []

    # ===============================
    # 🔁 GENERATION
    # ===============================
    for c in range(num_candidates):

        current_token = 1
        generated = []
        context = np.zeros(embedding_matrix.shape[1])

        temp = temperature + np.random.uniform(-0.05, 0.05)

        for pos in range(max_len):

            curr_emb = embedding_matrix[current_token]
            context = 0.5 * context + 0.5 * curr_emb

            x = np.concatenate([context, query_vec]).reshape(1, -1)

            logits, _ = engine.forward(
                x,
                query_anchor=query_vec,
                current_pos=pos,
                is_training=False
            )

            logits = logits / (temp + 1e-9)
            probs = engine.softmax(logits).astype(np.float64)

            for t in special_block:
                probs[0][t] = 0.0

            # SAFE NORMALIZATION
            probs = np.clip(probs, 0, None)
            s = np.sum(probs)

            if s <= 1e-12:
                probs = np.ones_like(probs) / len(probs[0])
            else:
                probs /= s

            # TOP-K
            top_k_idx = np.argpartition(probs[0], -top_k)[-top_k:]
            top_k_probs = probs[0][top_k_idx]

            top_k_probs = np.clip(top_k_probs, 0, None)
            s = np.sum(top_k_probs)

            if s <= 1e-12:
                top_k_probs = np.ones_like(top_k_probs)
            else:
                top_k_probs /= s

            top_k_probs = top_k_probs / np.sum(top_k_probs)

            if not np.isfinite(top_k_probs).all():
                top_k_probs = np.ones_like(top_k_probs) / len(top_k_probs)

            next_token = np.random.choice(top_k_idx, p=top_k_probs)

            if next_token == eos_token:
                break

            generated.append(next_token)
            current_token = next_token

        words = [vocab.idx2word.get(t, "") for t in generated]
        sentence = " ".join(words)

        sent_vec = embedder.encode(sentence)

        sim = np.dot(query_vec, sent_vec) / (
            np.linalg.norm(query_vec) * np.linalg.norm(sent_vec) + 1e-9
        )

        print(f"\n--- Candidate {c+1} ({sim:.3f}) ---")
        print(sentence)

        all_candidates.append(words)
        scores.append(sim)

    # ===============================
    # 🧠 BEST PICK
    # ===============================
    best_tokens = all_candidates[int(np.argmax(scores))]

    clean = []
    seen = set()

    for w in best_tokens:
        if w and w not in seen:
            seen.add(w)
            clean.append(w)

    # ===============================
    # 🔥 EXTRACT NUMBER + CATEGORY
    # ===============================
    number = None
    category = None

    for w in clean:
        if any(c.isdigit() for c in w) and "%" not in w:
            number = w

        if w in ["safe", "critical", "semi-critical", "over-exploited"]:
            category = w

    # ===============================
    # 🔥 GEO GROUNDING
    # ===============================
    district = detected_district
    state = detected_state

    if not district:
        for w in clean:
            if w in district_to_state:
                district = w
                state = district_to_state[w]
                break

    if not district:
        district = "the region"
        state = "india"

    # ===============================
    # 🔥 FACTUAL GROUNDING (CORE 🔥)
    # ===============================
    if district in fact_db:

        fact = fact_db[district]

        state = fact["state"]
        number = fact["units"]
        category = fact["category"]

        print("📊 FACT OVERRIDE APPLIED")

    if not number:
        number = "data"

    if not category:
        category = "safe"

    # ===============================
    # 🔥 FINAL OUTPUT
    # ===============================
    # ===============================
    # 🔥 NATURAL LANGUAGE STYLES
    # ===============================

    templates = [

        # Normal formal
        f"According to the 2024 National Compilation, {district} in {state} has {number} units and is classified as {category}.",

        # Conversational
        f"The groundwater status of {district}, {state} is {category}, with around {number} units recorded.",

        # Analytical
        f"{district} in {state} falls under the '{category}' category, with approximately {number} groundwater units.",

        # Short answer
        f"{district} ({state}) is classified as {category} with {number} units.",

        # Slight explanation
        f"In {district}, {state}, groundwater is categorized as {category}, based on {number} assessed units."

    ]

    final_sentence = random.choice(templates)

    print("\n🏆 FINAL OUTPUT:\n")
    print(final_sentence)

    return final_sentence

test_queries = [
    # 1️⃣ Direct district + state
    "What is the groundwater status of Mandya in Karnataka?",

    # 2️⃣ Another district
    "Provide groundwater data for Pune in Maharashtra",

    # 3️⃣ Different state
    "Tell me the groundwater classification of Cuttack in Odisha",

    # 4️⃣ Question style variation
    "How is groundwater in Belagavi Karnataka classified?",

    # 5️⃣ Missing state (should still work via geo map)
    "What is the groundwater status of Jodhpur?",

    # 6️⃣ Explanation style
    "Explain groundwater condition in Nagaur Rajasthan",

    # 7️⃣ Slight noisy query
    "groundwater report for erode tamil nadu units classification",

    # 8️⃣ Another region
    "Give groundwater status of Gaya in Bihar",

    # 9️⃣ Edge case (unknown / rare district)
    "What is the groundwater status of UnknownDistrict in India?",

    # 🔟 Conceptual question (no district)
    "How are groundwater units classified as safe or critical?"
]


for i, q in enumerate(test_queries, 1):
    print(f"\n🔍 TEST {i}")
    print("="*40)
    print("QUERY:", q)
    print("="*40)

    vajra_generate_v4(
        engine,
        embedder,
        vocab,
        q,
        district_to_state,
        fact_db
    )

"""# Connection"""

!pip install flask flask-cors pyngrok

from flask import Flask, request, jsonify
from flask_cors import CORS
from pyngrok import ngrok

app = Flask(__name__)
CORS(app)

# ===============================
# 🔥 ADD THIS (IMPORTANT)
# ===============================
ngrok.set_auth_token("3Chca4L6XA3Nap5VRb6BaDxHwRX_QznQTK5L3HW88SkSYz2U")


# ===============================
# 🔥 SIMPLE INTENT DETECTION
# ===============================
def detect_intent(text):
    text = text.lower()

    greetings = ["hi", "hello", "hey", "good morning", "good evening"]
    endings = ["bye", "goodbye", "thanks", "thank you", "see you"]

    if any(g in text for g in greetings):
        return "greeting"

    if any(e in text for e in endings):
        return "ending"

    return "query"


# ===============================
# 💬 CHAT ENDPOINT
# ===============================
@app.route('/chat', methods=['POST'])
def chat():
    try:
        user_msg = request.json.get('message', '').strip()

        if not user_msg:
            return jsonify({"response": "Please enter a valid query."})

        intent = detect_intent(user_msg)

        if intent == "greeting":
            return jsonify({
                "response": "Hey 👋 I can help you with groundwater data across India. Ask me about any district or state!"
            })

        if intent == "ending":
            return jsonify({
                "response": "Glad I could help! 😊 If you have more questions about groundwater, feel free to ask anytime."
            })

        # 🔥 YOUR MODEL
        result = vajra_generate_v4(
            engine,
            embedder,
            vocab,
            user_msg,
            district_to_state,
            fact_db
        )

        if not result or "error" in str(result).lower():
            result = "I couldn't find reliable groundwater data for that query. Try specifying district and state."

        return jsonify({"response": result})

    except Exception as e:
        print("🔥 ERROR:", str(e))
        return jsonify({
            "response": "Something went wrong while processing your request.",
            "error": str(e)
        })


# ===============================
# 🌍 START SERVER + NGROK (FIXED)
# ===============================

# start ngrok tunnel
public_url = ngrok.connect(5000)
print("🌍 Public URL:", public_url)

# 🔥 IMPORTANT: use use_reloader=False in Colab
app.run(port=5000, use_reloader=False)

"""#Saving Model"""

from google.colab import drive
drive.mount('/content/drive')

# ===============================
# 💾 SAVE VAJRA MODEL
# ===============================
import pickle
import os

save_path = "/content/drive/MyDrive/vajra_model"

os.makedirs(save_path, exist_ok=True)

# 🔥 Save Engine
with open(f"{save_path}/engine.pkl", "wb") as f:
    pickle.dump(engine, f)

# 🔥 Save Vocab
with open(f"{save_path}/vocab.pkl", "wb") as f:
    pickle.dump(vocab, f)

# 🔥 Save Embedder (only matrix, not full model)
np.save(f"{save_path}/embedding_matrix.npy", embedder.embedding_matrix)

print("✅ Model saved successfully to Drive!")

# ===============================
# 📥 LOAD VAJRA MODEL
# ===============================
import pickle
import numpy as np

load_path = "/content/drive/MyDrive/vajra_model"

# 🔥 Load Engine
# 1. define classes first

# 2. load
engine = pickle.load(open(f"{load_path}/engine.pkl", "rb"))
vocab = pickle.load(open(f"{load_path}/vocab.pkl", "rb"))

# 3. embedder
embedder = VajraEmbedder(vocab)
embedder.embedding_matrix = np.load(f"{load_path}/embedding_matrix.npy")

# 4. token freq
from collections import Counter
token_counter = Counter()
for sample in train_manifold:
    token_counter.update(sample['response_indices'])

engine.token_freq = token_counter

print("✅ READY")
print("✅ Model loaded successfully from Drive!")